### ISSUE TITLE
Dose it support IPAM now ?

### ISSUE THREAD

**Issue by rootdeep** [kubevirt/ovs-cni#105]
The ovs-cni's version comes to v0.9.0, dose it support IPAM from this version？
If it still not own this feature, is there anothor tool to act as IPAM and used together? 
or is there a plan to implement IPAM?

**Comment by phoracek** [comment]
Hello. v0.9.0 does not. IPAM support was added in https://github.com/kubevirt/ovs-cni/pull/102 and it is a part of v0.10.0 https://github.com/kubevirt/ovs-cni/releases/tag/v0.10.0 which was just released.

**Comment by rootdeep** [comment]
@phoracek   Is there a bianary package attached to release?   Thank you team anyway.

**Comment by phoracek** [comment]
I can build one for you and attach it. However, there is no binary build automation (only for images), so there is no assurance there will always be a binary attached to a release.

Find the build here https://github.com/kubevirt/ovs-cni/releases/tag/v0.10.0.
