### ISSUE TITLE
Failed to connect to ovsdb error: Invalid socket file

### ISSUE THREAD

**Issue by parthyadav3105** [kubevirt/ovs-cni#119]
On creating pod with 2 ovs interface it gives error __"ovs": error in getting result from AddNetwork: failed to connect to ovsdb error: Invalid socket file, failed to clean up sandbox container__
How can I debug more to know the actual cause of issue.

The yaml definitions file works on other setup. Here are the yaml files used:
```ovs-net.yml```
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-net-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "vsperf-br0"
    }'
```
```pod.yml```
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ovs
  annotations:
    k8s.v1.cni.cncf.io/networks: ovs-net-1, ovs-net-1
spec:
  containers:
  - name: nginx-ovs
    image: nginx:1.7.9
    ports:
      - containerPort: 80
```

```kubectl describe pod nginx-ovs```
```
Name:         nginx-ovs
Namespace:    default
Priority:     0
Node:         worker/10.10.120.21
Start Time:   Sat, 16 May 2020 13:48:19 -0700
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: ovs-net-1, ovs-net-1
              k8s.v1.cni.cncf.io/networks-status: 
Status:       Pending
IP:           
IPs:          <none>
Containers:
  nginx-ovs:
    Container ID:   
    Image:          nginx:1.7.9
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tw2c7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-tw2c7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tw2c7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age              From               Message
  ----     ------                  ----             ----               -------
  Normal   Scheduled               17s              default-scheduler  Successfully assigned default/nginx-ovs to worker
  Warning  FailedCreatePodSandBox  9s               kubelet, worker    Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "cf902dc941fa85325b871bcb93caa0298a9a8c1281b707150249a2cae984db68" network for pod "nginx-ovs": networkPlugin cni failed to set up pod "nginx-ovs_default" network: Multus: [default/nginx-ovs]: error adding container to network "ovs-net-1": delegateAdd: error invoking DelegateAdd - "ovs": error in getting result from AddNetwork: failed to connect to ovsdb error: Invalid socket file, failed to clean up sandbox container "cf902dc941fa85325b871bcb93caa0298a9a8c1281b707150249a2cae984db68" network for pod "nginx-ovs": networkPlugin cni failed to teardown pod "nginx-ovs_default" network: delegateDel: error invoking DelegateDel - "ovs": error in getting result from DelNetwork: failed to connect to ovsdb error: Invalid socket file / delegateDel: error invoking DelegateDel - "ovs": error in getting result from DelNetwork: failed to connect to ovsdb error: Invalid socket file]
  Normal   SandboxChanged          8s (x2 over 9s)  kubelet, worker    Pod sandbox changed, it will be killed and re-created.

```

The name of the bridge is __vsperf-br0__
The setup has one worker node and one master node.
The worker node has ovs installed. And ovs-daemonset.yml is deployed in the cluster.

**Comment by phoracek** [comment]
Hello Parth.

My guess would be that the socket is not available on the expected default path `/var/run/openvswitch/db.sock.`. Would you try logging in the guest and call `ovs-vsctl show` to see if OVS is working in general and if it is, call `ovs-vsctl show --db=unix:/var/run/openvswitch/db.sock` to see if it is on the path we expect?

**Comment by parthyadav3105** [comment]
Thanks, VSperf builds ovs to a different path. And the socket file was located at ```/usr/local/var/run/openvswitch/db.sock``` 
I rebuilt the plugin with a different path in [NewOvsBridgeDriver()](https://github.com/kubevirt/ovs-cni/blob/master/pkg/ovsdb/ovsdb.go#L59) function.
It works.

Would it make sense to add ```socketFile: path/to/socket/file``` to netConf so that plugin can override socket file path?

**Comment by phoracek** [comment]
It would be possible, but I don't like that option. It mixes the network configuration with deployment configuration. Rebuilding is a dramatic measure. You can accomplish the same effect by changing the mount path for OVS daemon set: https://github.com/kubevirt/ovs-cni/blob/master/examples/ovs-cni.yml#L67. Would it work for you? If it does, making the value configurable during templating in https://github.com/kubevirt/ovs-cni/blob/master/manifests/ovs-cni.yml.in#L67 may be a good middle ground.

**Comment by parthyadav3105** [comment]
Yeah, I did that also, it solved my half problem. Second half was the the change at plugin.

I agree with you, It would add complexity with Network Configuration. Maybe adding a script at VSperf for ovs-cni installation be a good option.

I am closing the issue.
Thanks.
