### ISSUE TITLE
[ovs-cni] Apply ovs-cni.yaml fail

### ISSUE THREAD

**Issue by willie-hsueh-666** [kubevirt/ovs-cni#131]
Hi,
We would like to set up ovs-cni.yaml on K8S. Below is our command:
kubectl apply -f ovs-cni.yaml

but found that the ovs-cni pod crash
kubectl get pod --all-namespaces
kube-system            ovs-cni-amd64-sg5c2                         0/1     CrashLoopBackOff   1          7s

and the container log is below
kubectl logs -f ovs-cni-amd64-sg5c2 -n kube-system --all-containers
I1012 03:18:41.081822       1 main.go:44] Found the OVS socket
F1012 03:18:41.082910       1 main.go:56] Failed to create a new marker object: Error creating the ovsdb connection: failed to connect to ovsdb error: dial unix /host/var/run/openvswitch/db.sock: connect: connection refused

Could you help to check this problem?

Please refer the attachment for our cni-ovs.yaml.
[cni-ovs.txt](https://github.com/kubevirt/ovs-cni/files/5364353/cni-ovs.txt)

Thanks,
Willie

**Comment by phoracek** [comment]
Hello @willie-hsueh-666 , 

do you have Open vSwitch installed and running on your host? It is a prerequisite for ovs-cni.

If so, in which version?

Would you try using the latest release v0.14.0?

**Comment by willie-hsueh-666** [comment]
Hi @phoracek 
Yes, we already installed the Open vSwitch and running on our host.
The version is below
ovs-vsctl (Open vSwitch) 2.14.90
DB Schema 8.2.0

Thanks,
Willie

**Comment by phoracek** [comment]
Please use the recent version v0.14.0, the one you use was built against quite an old version of OVS.

Also, would you verify that /var/run/openvswitch/db.sock really has the OVS socket on your host? Log in to the host and call:

```
ovs-vsctl --db unix:///var/run/openvswitch/db.sock show
```
