### ISSUE TITLE
OVS-CNI does not supprt tcp package between vms in different nodes

### ISSUE THREAD

**Issue by lixuehui08** [kubevirt/ovs-cni#145]
Hi

https://github.com/kubevirt/ovs-cni/blob/master/docs/demo.md

like this demo,  i build two vms using ovs-cni network,  this two virtual machines can ping each other and send UDP packets，but can not establish TCP connection。

Do you have this problem？

Relevant situations are shown in the figure below 

1、node‘s ovs port info 
![image](https://user-images.githubusercontent.com/75360526/103070461-7449c980-45fc-11eb-9af0-3d3eaf6a6daf.png)

2、vm‘s ping info
![image](https://user-images.githubusercontent.com/75360526/103071280-41a0d080-45fe-11eb-8334-ddd15e5960c5.png)

3、vm‘s udp info
![image](https://user-images.githubusercontent.com/75360526/103071309-4c5b6580-45fe-11eb-9c42-a8b30a534c76.png)

4、vm‘s tcp info
![image](https://user-images.githubusercontent.com/75360526/103071329-567d6400-45fe-11eb-8965-67cf65f8d393.png)
![image](https://user-images.githubusercontent.com/75360526/103071746-35694300-45ff-11eb-8373-96063c0e9bb3.png)

Thanks everyone~

**Comment by niloysh** [comment]
@lixuehui08 I'm facing the same issue. How did you solve it?
