### ISSUE TITLE
Support multiple nodes and OCP in local cluster

### ISSUE THREAD

**Issue by phoracek** [kubevirt/ovs-cni#3]
As discussed in https://github.com/kubevirt/ovs-cni/pull/1, it is desirable to test the code with multiple nodes and on different platforms too. In order to accomplish that, we should copy more of KubeVirt cluster helpers.

It is not clear to me yet how to do it, not pile unused and unrelated code from kubevirt here yet.

**Comment by SchSeba** [comment]
I will take this one

**Comment by phoracek** [comment]
Resolved in #5
