### ISSUE TITLE
Not all supported platforms offer Go 1.10 or higher

### ISSUE THREAD

**Issue by phoracek** [kubevirt/ovs-cni#6]
In the current state, with using network namespaces from Go, we enforce Go 1.10, since this code cannot be compiled on Go 1.9 or lower [1]. However, at this moment we need to work with Go 1.9 to support all platforms.

We should create a temporary workaround to work in container network namespace using `nsenter` or `ip netns`.

This code should be reverted and issue closed as soon as Go 1.9 platforms support is dropped.

[1] https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix

**Comment by SchSeba** [comment]
Can we leave the current implementation on a new branch?

**Comment by phoracek** [comment]
We could, but not sure if it's worth it. Almost finished the new
implementation and it's not that big of a change, plus we have got revert.

**Comment by SchSeba** [comment]
OK works for me

**Comment by phoracek** [comment]
WIP PR pushed https://github.com/kubevirt/ovs-cni/pull/7

**Comment by yuvalif** [comment]
which platforms don't support go.1.10? seems like mac/win/linux are supported: https://golang.org/dl/

**Comment by phoracek** [comment]
This repository master will require Go 1.10, 1.9 will be handled on a separate private branch to not block further development.
