### ISSUE TITLE
execute: `kubectl apply -f https://raw.githubusercontent.com/kubevirt/ovs-cni/master/examples/kubernetes-ovs-cni.yml`

### ISSUE THREAD

**Issue by xichengliudui** [kubevirt/ovs-cni#72]
I use `kubeadm init` initialize the cluster, and  install cni according to `https://github.com/kubevirt/ovs-cni/blob/master/docs/deployment-on-arbitrary-cluster.md` file, the result is:

![image](https://user-images.githubusercontent.com/40875627/54739316-9bd35d00-4bf2-11e9-874b-704b6f14c61d.png)

execute：kubectl describe po  ovs-cni-amd64-8v9gm --namespace=kube-system

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  33m (x3 over 33m)    default-scheduler  0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  9m22s (x5 over 14m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.
```
Please do not care about the first warning, I have deleted another node. I would like to ask why the mismatch is missing something？

**Comment by xichengliudui** [comment]
Has ovs specified any labels?

**Comment by SchSeba** [comment]
Hi @xichengliudui as I can see from your log looks like you don't have a primary network plugins.

ovs-cni is a secondary network using [multus](https://github.com/intel/multus-cni) and only provide a L2 network connectivity to a ovs bridge without assigning ip address on the interface.

**Comment by xichengliudui** [comment]
Thank you for your answer, because I use ovs plug-in once, may I ask what I need to do?

**Comment by SchSeba** [comment]
I think you can take a look on this document 
https://github.com/kubevirt/ovs-cni/blob/master/docs/deployment-on-arbitrary-cluster.md

But again you need a functional cluster with a primary network plugin ready.
You can install flannel or calico for that

**Comment by xichengliudui** [comment]
Thanks.
I created it with this file, but can ovs not replace calico or flannel as a web plug-in for k8s?

**Comment by SchSeba** [comment]
no this works only as a secondary network no as primary one.
If you want a primary network based on ovs you can deploy [ovs-kubernetes](https://github.com/openvswitch/ovn-kubernetes)

**Comment by xichengliudui** [comment]
Yes, I want ovs to be the main network of my cluster. Thank you for your patient reply
