### ISSUE TITLE
can't use ovs cni on ocp4 without workarounds

### ISSUE THREAD

**Issue by karmab** [kubevirt/ovs-cni#74]
on ocp4, the ovs cni plugin suffers from two issues:
- the rhcos nodes miss the libunbound.so.2 library.
  as a workaround, i copied the library from the ovs pods to /root on all the nodes and added this path to ld
  
```
  echo /root > /etc/ld.so.conf.d/root.conf
  ldconfig
 ``` 

- the path for searching cni plugins is different so i had to manually copy the ovs plugin binary to the proper place

```
cp /opt/cni/bin/ovs /var/lib/cni/bin
```

**Comment by phoracek** [comment]
Thanks for reporting this @karmab, we still don't have an easy way to test on OCP4... Will look into it.

**Comment by SchSeba** [comment]
This issue should be fixed now with https://github.com/kubevirt/ovs-cni/pull/78
